all: TCPend.class

TCPend.class: TCPend.java TCPEndHost.java GBNSegment.java Sender.java Receiver.java HandshakeType.java MaxRetransmitException.java SegmentChecksumMismatchException.java UnexpectedFlagException.java
	javac $^
